### ISSUE TITLE
f.sql enhancement

### ISSUE THREAD

**Issue by patrickjolliffe** [tanelpoder/tpt-oracle#43]
Would you accept a PR to change it to:
where upper(view_definition) like upper('%&1%') OR upper(view_name) like upper('%&1%');

(I know i should probably just create the PR then you reject/accept as you see fit, but whatever)

**Comment by tanelpoder** [comment]
Yeah, it would be nice to make (almost) all of my scripts more consistent regarding commadn line arguments. So with any small enough changes that are clearly inconsistent (because I sometimes create the scripts on the spot while working on some other problem), feel free to submit a PR right away (as it's a simple change and not too much work).

But for any bigger changes, I think opening an issue to discuss it first (like you did right now) is a good way to start.

**Comment by patrickjolliffe** [comment]
Done!

**Comment by tanelpoder** [comment]
Merged, thanks! 

By the way, should you do any bigger contributions to other scripts in the future (I have ideas :-) then feel free to add your name to the header too (into an updates/changes section)
